---
name: Linting

on: [push]

jobs:
  verify:
    runs-on: [ubuntu-latest]
    
    strategy:
      matrix:
        python-version: [3.8]
        linter: [flake8, mypy, yapf]
      
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install --upgrade pip tox
    - run: tox -e ${{ matrix.linter }}
