---
name: Linting

on:
  pull_request:
    branches: [master]

jobs:
  verify:
    runs-on: [ubuntu-latest]
    
    strategy:
      matrix:
        linter: [flake8, mypy, yapf, safety]
        python-version: [3.6, 3.7, 3.8]
        include:
          - linter: flake8
            python-version: 3.8
          - linter: yapf
            python-version: 3.8
          - linter: safety
            python-version: 3.8
      
    steps:
    - uses: actions/cache@v1.1.0
      with:
        path: .tox
        key: tox-env
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - run: pip install --upgrade pip tox
    - run: tox -e ${{ matrix.linter }}
  
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: typingcov_${{ env.GITHUB_SHA_SHORT }}
        path: typingcov
      if: matrix.linter == 'mypy'
