---
name: ShiftLeft Scan

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 20 * * 4"

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-python@v2
    - run: |
        pip install --upgrade pip setuptools wheel
    - run: |
        python setup.py build
        python setup.py install
    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
        type: python
    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports
