---
name: "ShiftLeft"

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 20 * * 4"

jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout 'HEAD^2'
        if: ${{ github.event_name == 'pull_request' }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.x

      - run: |
          pip install --upgrade pip setuptools wheel
      - run: |
          python setup.py build
          python setup.py install

      - name: Perform ShiftLeft Scan
        uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
        with:
          output: reports
          type: python
      - name: Upload report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports
